import React, { useEffect, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Dashboard from "../../components/Dashboard";
import { checkAuthStatus, getTickets } from "../../utils/functions";
import Loading from "../../components/Loading";

const dashboard = () => {
	const [loading, setLoading] = useState(true);
	const [openTickets, setOpenTickets] = useState([]);
	const [inprogressTickets, setInProgressTickets] = useState([]);
	const [completedTickets, setCompletedTickets] = useState([]);
	const [user, setUser] = useState({});
	const router = useRouter();

	useEffect(() => {
		function beforeMount() {
			checkAuthStatus(setUser, setLoading, router);
			getTickets(setOpenTickets, setInProgressTickets, setCompletedTickets);
		}
		beforeMount();
	}, []);

	if (loading) return <Loading />;
	return (
		<div>
			<Head>
				<title>Dashboard | FirmSupport</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Dashboard
				completedTickets={completedTickets}
				inprogressTickets={inprogressTickets}
				openTickets={openTickets}
			/>
		</div>
	);
};

export default dashboard;
