import React, { useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { logIn } from "../../utils/functions";

const login = () => {
	const [email, setEmail] = useState("");
	const [password, setPassword] = useState("");
	const router = useRouter();

	const handleLogin = (e) => {
		e.preventDefault();
		logIn(email, setEmail, password, setPassword, router);
	};
	return (
		<div>
			<Head>
				<title>Staff Login | FirmSupport</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='w-full h-[100vh] flex flex-col items-center justify-center py-6 px-4'>
				<h2 className='text-3xl font-bold mb-6'>Staff Sign in</h2>
				<form
					className='flex flex-col md:w-[60%] w-full'
					onSubmit={handleLogin}
				>
					<label htmlFor='email'>Email</label>
					<input
						type='email'
						id='email'
						name='email'
						value={email}
						onChange={(e) => setEmail(e.target.value)}
						className='py-2 px-4 border-[1px] rounded border-gray-200 mb-4'
					/>
					<label htmlFor='password'>Password</label>
					<input
						type='password'
						id='password'
						name='password'
						value={password}
						onChange={(e) => setPassword(e.target.value)}
						className='py-2 px-4 border-[1px] rounded border-gray-200 mb-4'
					/>
					<button className='p-3 bg-[#314484] rounded text-[#F4F8FB] w-[200px] hover:bg-[#2267D3]'>
						Sign in
					</button>
				</form>
				<p className='mt-10 text-sm text-gray-400 text-center'>
					&copy; Copyright {new Date().getFullYear()} FirmSupport
				</p>
			</main>
		</div>
	);
};

export default login;
